apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-toolbox

images:
- name: openshift-toolbox
  newName: quay.io/noseka1/openshift-toolbox
  newTag: basic

configMapGenerator:
- name: openshift-toolbox-init
  files:
  - init.sh

resources:
- openshift-toolbox-ns.yaml
- openshift-toolbox-deploy.yaml
- openshift-toolbox-sa.yaml
#- openshift-toolbox-home-pvc.yaml
#- openshift-toolbox-scc-role.yaml
#- openshift-toolbox-scc-rolebinding.yaml
#- openshift-toolbox-cluster-admin-clusterrolebinding.yaml

patchesStrategicMerge:
#- openshift-toolbox-deploy-hostNetwork.yaml
#- openshift-toolbox-deploy-hostPID.yaml
#- openshift-toolbox-deploy-hostIPC.yaml
#- openshift-toolbox-deploy-privileged.yaml
#- openshift-toolbox-deploy-home.yaml
#- openshift-toolbox-deploy-hostPath.yaml
#- openshift-toolbox-deploy-nodeName.yaml
