apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toolbox-container

images:
- name: toolbox-container
  newName: quay.io/noseka1/toolbox-container
  newTag: basic

configMapGenerator:
- name: toolbox-container-init
  files:
  - init.sh

resources:
- toolbox-container-ns.yaml
- toolbox-container-deploy.yaml
- toolbox-container-sa.yaml
#- toolbox-container-home-pvc.yaml
#- toolbox-container-scc-role.yaml
#- toolbox-container-scc-rolebinding.yaml
#- toolbox-container-cluster-admin-clusterrolebinding.yaml

patchesStrategicMerge:
#- toolbox-container-deploy-hostNetwork.yaml
#- toolbox-container-deploy-hostPID.yaml
#- toolbox-container-deploy-hostIPC.yaml
#- toolbox-container-deploy-privileged.yaml
#- toolbox-container-deploy-home-pvc.yaml
#- toolbox-container-deploy-hostPath.yaml
#- toolbox-container-deploy-nodeName.yaml
