apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-toolbox
spec:
  template:
    spec:
      containers:
      - name: openshift-toolbox
        volumeMounts:
        - name: home
          mountPath: /home/toolbox
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: openshift-toolbox-home
