apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-toolbox
spec:
  template:
    spec:
      containers:
      - name: openshift-toolbox
        volumeMounts:
        - name: host
          mountPath: /host
          mountPropagation: Bidirectional
      volumes:
      - name: host
        hostPath:
          path: /
