apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: run
          mountPath: /run
      volumes:
      - name: run
        hostPath:
          path: /run
