apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: root
          mountPath: /root
      volumes:
      - name: root
        hostPath:
          path: /root
