apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        command:
        - /bin/bash
        args:
        - -c
        - '
          trap : TERM INT &&
          sleep infinity & wait
          '
