apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
          readonly: true
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
