apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: dev
          mountPath: /dev
      volumes:
      - name: dev
        hostPath:
          path: /dev
